name: pymangle CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
            - releases/*

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ ubuntu-latest ]
                py: [ "3.11" ]
                CC: [ gcc ]
                CXX: [ g++ ]

        defaults:
            run:
                # cf. https://github.com/conda-incubator/setup-miniconda#important
                shell: bash -l {0}

        steps:
            - uses: actions/checkout@v2
            - uses: conda-incubator/setup-miniconda@v2
              with:
                  python-version: ${{ matrix.pyver }}
                  channels: conda-forge,defaults
                  channel-priority: strict
                  show-channel-urls: true
                  miniforge-version: latest

            - name: Install deps
              run: |
                conda config --set always_yes yes
                conda install numpy pytest flake8

            - name: Install pymangle
              run:
                pip install .

            - name: lint
              run: |
                flake8 pymangle

            - name: Run tests
              run: |
                pytest -vv tests/
